apiVersion: v1
kind: ConfigMap
metadata:
  name: dso202-config
  namespace: dso202-assignment-01
data:
  DB_HOST: "db-svc"
  DB_PORT: "5432"
  DB_NAME: "taskdb"
  APP_PORT: "8080"
  CORS_ORIGIN: "*"
  POSTGRES_DB: "taskdb"
  BACKEND_URL: "http://backend-svc:8080"