apiVersion: v1
kind: ResourceQuota
metadata:
  name: dso202-quota
  namespace: dso202-assignment-01
spec:
  hard:
    pods: "4"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dso202-limitrange
  namespace: dso202-assignment-01
spec:
  limits:
    - type: Container
      default:
        cpu: "500m"
        memory: "256Mi"
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"