apiVersion: v1
kind: Secret
metadata:
  name: dso202-secret
  namespace: dso202-assignment-01
type: Opaque
data:
  DB_USER: dGFza3VzZXI=
  DB_PASSWORD: dGFza3Bhc3MxMjM=
  POSTGRES_USER: dGFza3VzZXI=
  POSTGRES_PASSWORD: dGFza3Bhc3MxMjM=
  