apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dso202-viewer-binding
  namespace: dso202-assignment-01
subjects:
  - kind: ServiceAccount
    name: dso202-viewer
    namespace: dso202-assignment-01
roleRef:
  kind: Role
  name: dso202-pod-and-service-reader
  apiGroup: rbac.authorization.k8s.io